variables:
  fatsDir: '$(system.defaultWorkingDirectory)/../fats'
  fatsRepo: projectriff/fats
  fatsRefspec: 1a462b4a35ebdb66d678d648b5803fa498871ec6 # master as of 2019-07-09
  tillerNamespace: kube-system
  tillerServiceAccount: tiller

jobs:

- job: stage
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: ./ci/fats-fetch.sh $(fatsDir) $(fatsRefspec) $(fatsRepo)
    displayName: 'Fetch FATS'
  - bash: |
      $(fatsDir)/install.sh helm
      $(fatsDir)/install.sh gcloud
      $(fatsDir)/install.sh ytt 0.14.0
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    displayName: 'Install tools'
  - bash: |
      helm init --client-only
      make publish-snapshot
    displayName: 'Stage projectriff chart artifacts'
  displayName: 'Stage chart'

- job: test
  dependsOn: stage
  strategy:
    matrix:
      minikube:
        imageName: ubuntu-16.04
        qualifier: minikube
        cluster: minikube
        registry: dockerhub
      gke:
        imageName: ubuntu-16.04
        qualifier: gke
        cluster: gke
        registry: gcr
  pool:
    vmImage: $(imageName)
  variables:
    CLUSTER:  '$(cluster)'
    REGISTRY: '$(registry)'
    CLUSTER_NAME: 'charts-$(Build.BuildId)-$(qualifier)'
    NAMESPACE: '$(CLUSTER_NAME)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
  - bash: ./ci/fats-fetch.sh $(fatsDir) $(fatsRefspec) $(fatsRepo)
    displayName: 'Fetch FATS'
  - bash: |
      $(fatsDir)/install.sh kubectl
      $(fatsDir)/install.sh riff
      $(fatsDir)/install.sh helm
      $(fatsDir)/install.sh gcloud
    displayName: 'Install tools'
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
  - bash: $(fatsDir)/start.sh
    displayName: 'Start FATS'
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
  - bash: |
      set -o errexit
      set -o nounset
      set -o pipefail

      source $(fatsDir)/.configure.sh

      kubectl create serviceaccount $(tillerServiceAccount) -n $(tillerNamespace)
      kubectl create clusterrolebinding "$(tillerServiceAccount)-cluster-admin" --clusterrole cluster-admin --serviceaccount "$(tillerNamespace):$(tillerServiceAccount)"
      helm init --wait --service-account $(tillerServiceAccount)
      helm repo add projectriff-snapshots https://projectriff.storage.googleapis.com/charts/snapshots
      helm repo update

      helm install projectriff-snapshots/projectriff-riff --name riff --devel --set istio.enabled=true --set global.k8s.service.type=${K8S_SERVICE_TYPE}
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    displayName: 'Install riff'
  - bash: ./ci/run-tests.sh
    displayName: 'Run FATS'
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      FATS_DIR: $(fatsDir)
      FATS_REFSPEC: $(fatsRefspec)
  - bash: ci/diagnostics.sh
    condition: failed()
    displayName: 'Collect diagnostics'
  - bash: helm delete riff
    condition: always()
    displayName: 'Uninstall riff'
  - bash: $(fatsDir)/cleanup.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
    condition: always()
    displayName: 'Cleanup FATS'
  displayName: 'Test'