#@ load("@ytt:overlay", "overlay")

#! replace LoadBalancer services with NodePorts

#@overlay/match by=overlay.subset({ "apiVersion": "v1", "kind": "Service", "spec": { "type": "LoadBalancer" } }), missing_ok=True
---
spec:
  #@overlay/replace
  type: "NodePort"
