apiVersion: v1
name: riff-knative-runtime
description: knative runtime for riff
home: https://projectriff.io
sources:
  - https://github.com/projectriff/system
icon: https://projectriff.io/images/riff.png
tillerVersion: '>=2.14'
