application-builder: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-application-clusterbuilder-0.5.0-snapshot-20191031152125-d325442f41fc9265.yaml
function-builder: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-function-clusterbuilder-0.5.0-snapshot-20191031152125-d325442f41fc9265.yaml
