#@ load("@ytt:overlay", "overlay")

#! Order API service and its backing services: related https://github.com/k14s/kapp/issues/12

#@overlay/match by=overlay.subset({"kind": "APIService"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule: "upsert after upserting cert-manager-deployment"
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule.0: "delete before deleting cert-manager-deployment"

#@overlay/match by=overlay.subset({"kind": "ValidatingWebhookConfiguration"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule: "upsert after upserting cert-manager-deployment"
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule.0: "delete before deleting cert-manager-deployment"

#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="0+"
---
#! update to use apps/v1 so that kapp can wait on Deployment
#! (https://github.com/k14s/kapp/blob/master/docs/apply-waiting.md)
apiVersion: apps/v1
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: "cert-manager-deployment"

#@overlay/match by=overlay.subset({"kind": "Service"}),expects="0+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/change-group: "cert-manager-deployment"

#! Remove _unnecessary_ status blocks as make kapp show CRDs as changed

#@overlay/match by=overlay.all,expects="1+"
---
#@overlay/match missing_ok=True
#@overlay/remove
status:
