apiVersion: v1
name: cert-manager
appVersion: v0.10.1
description: riff support for cert-manager
home: https://projectriff.io
sources:
  - https://github.com/jetstack/cert-manager
icon: https://projectriff.io/images/riff.png
tillerVersion: '>=2.13'
