apiVersion: v1
name: riff-core-istio
description: istio ingress for riff core runtime
home: https://projectriff.io
sources:
  - https://github.com/projectriff/system
icon: https://projectriff.io/images/riff.png
tillerVersion: '>=2.13'
